export const scenes: Record<string, { label: string; image: string }> = {
  office:{label:'物理办公室',image:'bg01'},classroom:{label:'物理教室',image:'bg06'},
  corridor:{label:'教学楼走廊',image:'bg04'},garden:{label:'校园 · 花坛与校门',image:'bg16'},
  gate:{label:'校门口',image:'bg16'},lab:{label:'物理展示 · 气球小车',image:'bg10'},
  home:{label:'家里',image:'bg18'},dinner:{label:'退休聚餐',image:'bg21'},
  bg01:{label:'物理办公室·入职第一天',image:'bg01'},
  bg02:{label:'物理教室·跟课听讲',image:'bg02'},
  bg03:{label:'语文组办公室·打听师傅',image:'bg03'},
  bg04:{label:'教学楼走廊·第一次熟悉校园',image:'bg04'},
  bg05:{label:'物理办公室·课间答疑',image:'bg05'},
  bg06:{label:'物理教室·摩擦力争议',image:'bg06'},
  bg07:{label:'新班教室·后排与讲台旁座位',image:'bg07'},
  bg08:{label:'物理办公室·安静谈话',image:'bg08'},
  bg09:{label:'物理实验室·小组重新参与',image:'bg09'},
  bg10:{label:'物理实验室·气球小车调试',image:'bg10'},
  bg11:{label:'物理展示教室·校园开放日',image:'bg11'},
  bg12:{label:'校门迎宾区·开放日',image:'bg12'},
  bg13:{label:'教室·家长会散场后',image:'bg13'},
  bg14:{label:'物理办公室·学期末复盘',image:'bg14'},
  bg15:{label:'物理教室·作业裁员大会',image:'bg15'},
  bg16:{label:'校园花坛与下楼小路·栀子花',image:'bg16'},
  bg17:{label:'物理办公室·毕业志愿咨询',image:'bg17'},
  bg18:{label:'冬日清晨·家门口玄关',image:'bg18'},
  bg19:{label:'冬日学校·清晨办公室',image:'bg19'},
  bg20:{label:'物理教室·最后一堂课',image:'bg20'},
  bg21:{label:'退休聚餐·学校附近小包间',image:'bg21'},
};
